version: '2'
services:
    gcp-emulator:
        build:
            context: .
            dockerfile: Dockerfile.gcp-emulator
        ports:
            - "8085:8085"
        environment:
            PUBSUB_EMULATOR_HOST: 0.0.0.0:8085
            GOOGLE_APPLICATION_CREDENTIALS: /certs/file.txt # Define this!
    comet:
        build:
            context: .
            dockerfile: Dockerfile.comet
        environment:
            PROJECT_ID: comet-example-project
            PUBSUB_TOPIC: comet-example-topic
            PUBSUB_SUBSCRIPTION: comet-example-subscription
            PUBSUB_SCHEMA: http
            PUBSUB_HOSTNAME: gcp-emulator
            PUBSUB_PORT: 8085
            GOOGLE_APPLICATION_CREDENTIALS: /certs/file.txt # Define this!
            PUBSUB_EMULATOR_HOST: gcp-emulator:8085
        depends_on:
            - gcp-emulator 
        volumes:
            - ${PWD}/certs:/certs
            - ${PWD}/comet-example.db:/usr/src/app/comet-example.db
        command: [ "backup" ] 
    comet-api:
        build:
            context: .
            dockerfile: Dockerfile.comet
        ports:
            - "5000:5000"
        environment:
            PROJECT_ID: comet-example-project
            PUBSUB_TOPIC: comet-example-topic
            PUBSUB_SUBSCRIPTION: comet-example-subscription
            PUBSUB_HOST: http://gcp-emulator:8085
            FLASK_RUN_PORT: 5000
            FLASK_RUN_HOST: 0.0.0.0
            PUBSUB_EMULATOR_HOST: gcp-emulator:8085
        depends_on:
            - gcp-emulator  
        volumes:
            - ${PWD}/comet-example.db:/usr/src/app/comet-example.db
        command: [ "api" ]
volumes:
    certs:
    comet-example.db:
